services:
  postgres:
    container_name: "documents-db1"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=document_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=document_user'
    ports:
      - '6432:5432'
